table Category_Key
	lineageTag: dce8716f-e85e-4219-a913-8e77c97861d4

	column Key
		dataType: string
		lineageTag: 889f825d-d402-4ab7-94d3-44d9eb15d2b8
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7c9e1198-c10e-415c-bab3-b9209570c119
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Category_Key = m
		mode: import
		source =
				let
				    Origen = FacAlertNotification2,
				    Personalizado2 = Table.Distinct(#"Origen", {"Key"}),
				    Personalizado1 = Table.SelectColumns(Personalizado2, {"Key", "Category"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Personalizado1", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas1" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

