table DimOrganization
	lineageTag: fbf6f0e5-e14e-41d0-81b9-b6ddecf79377

	column OrganizationId
		dataType: string
		lineageTag: 54941779-ad4b-4567-b136-4ae6933c387c
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column AutoGeneratedAppId
		dataType: string
		lineageTag: e5b89dc5-77b3-4c2f-a2cf-472b8cec4d41
		summarizeBy: none
		sourceColumn: AutoGeneratedAppId

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: e72ce186-5251-4de8-9d71-a4387d84b10f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 6e473d28-c154-4b7a-b24a-04b4563c062f
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: dc547bae-b876-48f5-be66-6a6263360aad
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d4fdc856-abd8-4d63-b7c0-a58b67a6824c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column LanguageId
		dataType: string
		lineageTag: 940b1c56-e76c-45df-9d0b-114036d9edd5
		summarizeBy: none
		sourceColumn: LanguageId

		annotation SummarizationSetBy = Automatic

	column TimeZoneId
		dataType: string
		lineageTag: 00016290-cfcf-4c53-ae58-1249d243daf8
		summarizeBy: none
		sourceColumn: TimeZoneId

		annotation SummarizationSetBy = Automatic

	column Discriminator
		dataType: string
		lineageTag: 0a326d88-a147-418d-b040-f963ab095845
		summarizeBy: none
		sourceColumn: Discriminator

		annotation SummarizationSetBy = Automatic

	column ImageType
		dataType: string
		lineageTag: 66fbb936-5712-40d2-ab01-f577590fe6be
		summarizeBy: none
		sourceColumn: ImageType

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 1fdeca11-09c4-4799-89df-458835805b9e
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column VAT
		dataType: string
		lineageTag: f4328942-9bc1-448d-84b0-987a40e32d7a
		summarizeBy: none
		sourceColumn: VAT

		annotation SummarizationSetBy = Automatic

	column CompanyId
		dataType: string
		lineageTag: a2fa38e6-5623-440e-b9a3-8fac0b89eca4
		summarizeBy: none
		sourceColumn: CompanyId

		annotation SummarizationSetBy = Automatic

	column ParentDeparmentId
		dataType: string
		lineageTag: 33ecafdf-28c4-420a-8362-b8fa27f37e5e
		summarizeBy: none
		sourceColumn: ParentDeparmentId

		annotation SummarizationSetBy = Automatic

	column VisibleByOrganizationId
		dataType: string
		lineageTag: 2280c2f0-e19e-4219-b0c8-d05cb2b5d609
		summarizeBy: none
		sourceColumn: VisibleByOrganizationId

		annotation SummarizationSetBy = Automatic

	column Editable
		dataType: string
		lineageTag: 4c729136-84d6-4e85-ad78-96e5f97d5042
		summarizeBy: none
		sourceColumn: Editable

		annotation SummarizationSetBy = Automatic

	column scd_start
		dataType: string
		lineageTag: a8b15fbd-fd34-4bc7-89fc-31312965e95c
		summarizeBy: none
		sourceColumn: scd_start

		annotation SummarizationSetBy = Automatic

	column scd_end
		dataType: string
		lineageTag: 25a98abf-f08a-45bb-b266-43567a0e77e5
		summarizeBy: none
		sourceColumn: scd_end

		annotation SummarizationSetBy = Automatic

	column scd_version
		dataType: string
		lineageTag: cb2a73ea-40b2-4f31-ad2f-6298bf3250a8
		summarizeBy: none
		sourceColumn: scd_version

		annotation SummarizationSetBy = Automatic

	column scd_active
		dataType: string
		lineageTag: b943341d-6d84-482b-9353-e60162e00340
		summarizeBy: none
		sourceColumn: scd_active

		annotation SummarizationSetBy = Automatic

	column OrganizationPk
		dataType: string
		lineageTag: 590bde96-ea56-47ff-af14-4621a4e2145e
		summarizeBy: none
		sourceColumn: OrganizationPk

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: 11a41a3e-7e9f-42a9-ad5f-b542b5e1b4b6
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	column FacTravel
		dataType: string
		lineageTag: 1b7ff4d1-d659-4d6b-ac27-169689ad9d6f
		summarizeBy: none
		sourceColumn: FacTravel

		annotation SummarizationSetBy = Automatic

	partition DimOrganization-85e8af50-7857-4cd7-92d4-28e446397fec = m
		mode: import
		source =
				let
				    Origen = Sql.Database(Server, Database),
				    dbo_DimOrganization = Origen{[Schema="dbo", Item="DimOrganization"]}[Data],
				    #"Columna temporal añadida" = Table.AddColumn(dbo_DimOrganization, "AutoGeneratedAppId_Temp", each Text.Lower([AutoGeneratedAppId])),
				    #"Agrupados por AutoGeneratedAppId_Temp" = Table.Group(
				        #"Columna temporal añadida",
				        {"AutoGeneratedAppId_Temp"},
				        {{"TopRow", each Table.MaxN(_, "OrganizationPk", 1){0}, type table [OrganizationPk=Int64.Type, AutoGeneratedAppId=Text.Type, OtherColumns=Any.Type]}}
				    ),
				    #"Duplicados quitados" = Table.ExpandRecordColumn(
				        #"Agrupados por AutoGeneratedAppId_Temp",
				        "TopRow",
				        Table.ColumnNames(dbo_DimOrganization)
				    ),
				    #"Columna temporal quitada" = Table.RemoveColumns(#"Duplicados quitados", {"AutoGeneratedAppId_Temp"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columna temporal quitada", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas" = Table.RemoveColumns(FiltroDatos, {"FiltroDatos"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

