table DimVehicle
	lineageTag: 6caf23be-0828-4013-90db-c4988ca0c0ac

	column VehicleId
		dataType: string
		lineageTag: 705ea2a1-a1e8-4de0-b1a7-50eb622fde45
		summarizeBy: none
		sourceColumn: VehicleId

		annotation SummarizationSetBy = Automatic

	column SerializedExtendedData
		dataType: string
		lineageTag: 820fcaf0-aca6-4d33-802c-08ee46144a0d
		summarizeBy: none
		sourceColumn: SerializedExtendedData

		annotation SummarizationSetBy = Automatic

	column AutoGeneratedAppId
		dataType: string
		lineageTag: 88630397-395b-4acd-a2a2-e5bc31212577
		summarizeBy: none
		sourceColumn: AutoGeneratedAppId

		annotation SummarizationSetBy = Automatic

	column Plate
		dataType: string
		lineageTag: 5af58aa5-6ee9-4eb5-b10d-e5c3f3dacc3b
		summarizeBy: none
		sourceColumn: Plate

		annotation SummarizationSetBy = Automatic

	column SideCode
		dataType: string
		lineageTag: d3d49c38-9db6-4729-b29c-169ed5bf36f3
		summarizeBy: none
		sourceColumn: SideCode

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 7ffcab01-26c7-499a-9a9d-07377d6f9733
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: 4044b6a1-35c1-4d56-a05c-54d6d2932849
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column RegistrationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d302c8b-a040-46a3-813d-689ae533e245
		summarizeBy: none
		sourceColumn: RegistrationDate

		annotation SummarizationSetBy = Automatic

	column Handicapped
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c1cb93b8-c90e-49cb-a85a-26844ed27751
		summarizeBy: none
		sourceColumn: Handicapped

		annotation SummarizationSetBy = Automatic

	column Capacity
		dataType: int64
		formatString: 0
		lineageTag: 627f9433-3952-4dd8-a2d9-079e4773bd05
		summarizeBy: sum
		sourceColumn: Capacity

		annotation SummarizationSetBy = Automatic

	column VehicleLength
		dataType: double
		lineageTag: 59504c8b-1659-4208-a47b-eaeb48e2a3a7
		summarizeBy: sum
		sourceColumn: VehicleLength

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Disabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 10d16d4f-282c-4b30-9f7a-024d9633d140
		summarizeBy: none
		sourceColumn: Disabled

		annotation SummarizationSetBy = Automatic

	column scd_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 4bbb0873-89a8-46fa-ad7e-1f82d91d5ac2
		summarizeBy: none
		sourceColumn: scd_start

		annotation SummarizationSetBy = Automatic

	column scd_end
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b3bc576-fc5e-4ef8-89e4-4fd8c0a3438a
		summarizeBy: none
		sourceColumn: scd_end

		annotation SummarizationSetBy = Automatic

	column scd_version
		dataType: int64
		formatString: 0
		lineageTag: 136fcc04-329a-4a49-9019-67af0be734c1
		summarizeBy: sum
		sourceColumn: scd_version

		annotation SummarizationSetBy = Automatic

	column scd_active
		dataType: double
		lineageTag: 4ebec2d6-3ff4-49bf-87bd-fb2db3e8cd11
		summarizeBy: sum
		sourceColumn: scd_active

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VehiclePk
		dataType: int64
		formatString: 0
		lineageTag: 0a9ca516-2b7b-4146-92b4-31824073dca7
		summarizeBy: none
		sourceColumn: VehiclePk

		annotation SummarizationSetBy = Automatic

	column Vehículo = "["&DimVehicle[sidecode]&"] "&DimVehicle[Plate]
		lineageTag: fa6cb235-3817-4d85-b0b7-24921d4a6568
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrganizationAppId
		dataType: string
		lineageTag: ebae4ddb-3dc9-4476-85c0-9df679825286
		summarizeBy: none
		sourceColumn: OrganizationAppId

		annotation SummarizationSetBy = Automatic

	partition DimVehicle-bdad538d-07d4-47b4-8320-d7e8ae6bcc45 = m
		mode: import
		source =
				let
				    Origen = Sql.Database(Server, Database),
				    dbo_DimVehicle = Origen{[Schema="dbo",Item="DimVehicle"]}[Data],
				    #"Personalizada agregada" = Table.AddColumn(dbo_DimVehicle, "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

