table FacAlertNotification2
	lineageTag: 0ce558f8-1e01-40f6-9732-8d3f1bfcd2d5

	column Category
		dataType: string
		lineageTag: a10a4544-a64e-4806-8f54-ce7787dead36
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 478c7f1e-ed5b-4ef4-b4c1-2489e6d19241
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column ResourceKey
		dataType: string
		lineageTag: 11d5c6cf-7c0b-4cbb-be1e-9826877e930a
		summarizeBy: none
		sourceColumn: ResourceKey

		annotation SummarizationSetBy = Automatic

	partition FacAlertNotification2 = m
		mode: import
		source =
				let
				    Origen = Sql.Database(Server, Database),
				    dbo_DimAlertNotification = Origen{[Schema="dbo",Item="FacAlertNotification"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_DimAlertNotification,{"AlertNotificationId", "VehicleFk", "OrganizationAppId", "Timestamp", "Value", "ResourceParameters", "InsertDate", "AlertNotificationPk", "Priority"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas quitadas", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas1" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

