table LanguagesMapping
	lineageTag: c25d3a1b-bc6e-48bd-acbb-eeb727856466

	column Language
		dataType: string
		lineageTag: 860bc7bb-ae89-4c4d-81ff-ddd30198e34f
		summarizeBy: none
		sourceColumn: Language

		annotation SummarizationSetBy = Automatic

	column LanguageMapping
		dataType: string
		lineageTag: fbf64a6b-cc30-4dac-b91d-5d1704a7bb51
		summarizeBy: none
		sourceColumn: LanguageMapping

		annotation SummarizationSetBy = Automatic

	partition LanguagesMapping = m
		mode: import
		source = ```
				let
				    // Cargar la tabla Settings
				    Settings = Sql.Database(Server, Database){[Schema="dbo",Item="Settings"]}[Data],
				
				    // Obtener la lista de idiomas de la tabla Settings
				    LanguageSettings = Text.Split(List.First(Table.SelectRows(Settings, each [Setting] = "Languages")[Value]), "|"),
				
				    // Crear una tabla de mapeo dinámicamente a partir de los valores de Settings
				    IdiomasMap = Table.FromList(LanguageSettings, Splitter.SplitByNothing(), {"Language"}),
				
				    // Agregar una columna con los nombres completos del idioma (esto es un ejemplo, ajusta según tu lógica de nombres)
				    #"Agregar nombres completos" = Table.AddColumn(IdiomasMap, "LanguageMapping", each 
				        if [Language] = "ca" then "Catalan" 
				        else if [Language] = "en" then "English" 
				        else if [Language] = "es" then "Spanish" 
				        else if [Language] = "fr" then "French" 
				        else if [Language] = "en-US" then "English-US" 
				        else if [Language] = "pl" then "Polish"
				        else if [Language] = "gl" then "Galician"
				        else if [Language] = "el" then "Greek"
				        else [Language]),
				
				    #"Personalizada agregada" = Table.AddColumn(#"Agregar nombres completos", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

