table MeasuresTable
	lineageTag: dce75809-e5a3-4b52-b899-614029b33fa2

	measure UpperOrganzation = UPPER(SELECTEDVALUE(Resources[Organization]))
		lineageTag: 8d213a3d-590d-4d61-b59a-727b46a13c2a

	measure DateUpper = UPPER(SELECTEDVALUE(Resources[Date]))
		lineageTag: 09726601-7da3-485e-a2e2-ebff845298ee

	measure CategoryUpper = UPPER(SELECTEDVALUE(Resources[Category]))
		lineageTag: 66c62a23-324b-44bf-9e72-bd814b4d527e

	measure KeyUpper = UPPER(SELECTEDVALUE(Resources[Key]))
		lineageTag: 5b552473-a6ab-432c-a012-aea86219a335

	measure VehicleUpper = UPPER(SELECTEDVALUE(Resources[Vehicle]))
		lineageTag: f1b0fe11-936e-48e9-b94c-fe3d44b8491c

	measure PriorityUpper = UPPER(SELECTEDVALUE(Resources[Priority]))
		lineageTag: d4efd85a-8615-48ad-b6e8-d4fd035e1853

	partition MeasuresTable-2a2b2155-da3f-4263-92c2-52371ca7ac9f = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", Int64.Type}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

