table PriorityTypes
	lineageTag: 4d71597a-26d1-41f0-ad7f-27333fc2a62f

	column Priority_n
		dataType: string
		lineageTag: 4df362aa-2212-424b-a69c-6c3ff97229be
		summarizeBy: none
		sourceColumn: Priority_n

		annotation SummarizationSetBy = Automatic

	column Language
		dataType: string
		lineageTag: a86edbdd-a14b-44a5-bdde-405adf01ea9e
		summarizeBy: none
		sourceColumn: Language

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: bcfe7df5-7210-46aa-b881-bf9171fc7097
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Priority_description
		dataType: string
		lineageTag: 07f36bd3-5270-4193-9f61-7efe84e61b8f
		summarizeBy: none
		sourceColumn: Priority_description

		annotation SummarizationSetBy = Automatic

	partition PriorityTypes-0b4b4d3c-afca-45c1-8c5c-33cf96300040 = m
		mode: import
		source =
				let
				    Origen = Sql.Database(Server, Database),
				    dbo_Resources = Origen{[Schema="dbo",Item="Resources"]}[Data],
				    #"Consultas combinadas" = Table.NestedJoin(dbo_Resources, {"Language"}, LanguagesMapping, {"Language"}, "LanguagesMapping", JoinKind.Inner),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Consultas combinadas",{{"Language", "Language_ac"}}),
				    #"Se expandió LanguagesMapping" = Table.ExpandTableColumn(#"Columnas con nombre cambiado", "LanguagesMapping", {"LanguageMapping"}, {"Language"}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Se expandió LanguagesMapping",{"Language_ac"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas1", each ([Key] = "Critical" or [Key] = "High" or [Key] = "Low" or [Key] = "Medium" or [Key] = "VeryHigh")),
				    #"Columna condicional agregada" = Table.AddColumn(#"Filas filtradas", "Priority", each if [Key] = "Critical" then 25 else if [Key] = "High" then 15 else if [Key] = "VeryHigh" then 20 else if [Key] = "Low" then 5 else if [Key] = "Medium" then 10 else null),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columna condicional agregada",{{"Value", "Priority_description"}, {"Priority", "Priority_n"}, {"Key", "Priority"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado2", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

