table Resources_ResourceKey
	lineageTag: c1be1475-45e1-4b03-a17f-102738bc679d

	column Language
		dataType: string
		lineageTag: af856f37-14eb-42a1-a205-f3adda59ba0a
		summarizeBy: none
		sourceColumn: Language

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: f88ccdc8-58ef-44ba-9136-ea1c38d0ec5f
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 3ee4d8eb-85f5-41d3-bf62-723c824494fc
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Resources_ResourceKey = m
		mode: import
		source =
				let
				    Origen = Sql.Database(Server, Database),
				    dbo_Resources = Origen{[Schema="dbo",Item="Resources"]}[Data],
				     #"Consultas combinadas" = Table.NestedJoin(dbo_Resources, {"Language"}, LanguagesMapping, {"Language"}, "LanguagesMapping", JoinKind.RightOuter),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Consultas combinadas",{{"Language", "Language_ac"}}),
				    #"Se expandió LanguagesMapping" = Table.ExpandTableColumn(#"Columnas con nombre cambiado", "LanguagesMapping", {"LanguageMapping"}, {"Language"}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Se expandió LanguagesMapping",{"Language_ac"}),
				    #"Selección de recursos" = Table.TransformColumns(
				    Table.SelectRows(
				        #"Columnas quitadas1",
				        each Text.StartsWith([Key], "Notifications_")
				    ),
				    {"Key", each Text.Replace(_, "Notifications_", "")}
				),
				    #"Union ResourceKeys" = Table.NestedJoin(#"Selección de recursos", {"Key"}, ResourceKeys, {"ResourceKey"}, "ResourceKeys", JoinKind.Inner),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Union ResourceKeys",{"ResourceKeys"}),
				    #"Valor reemplazado (blank)" = Table.ReplaceValue(#"Columnas quitadas","Clau","",Replacer.ReplaceText,{"Value"}),
				    #"Valor reemplazado1 (blank)" = Table.ReplaceValue(#"Valor reemplazado (blank)","Key","",Replacer.ReplaceText,{"Value"}),
				    #"Valor reemplazado2 (blank)" = Table.ReplaceValue(#"Valor reemplazado1 (blank)","Clave","",Replacer.ReplaceText,{"Value"}),
				    #"Valor reemplazado3 (blank)" = Table.ReplaceValue(#"Valor reemplazado2 (blank)","Key","",Replacer.ReplaceText,{"Key"}),
				    #"Consulta anexada1" = Table.Combine({#"Valor reemplazado3 (blank)", NullsTable}),
				    #"Personalizada agregada" = Table.AddColumn(#"Consulta anexada1", "FiltroDatos", each 0),
				    FiltroDatos = Table.SelectRows(#"Personalizada agregada", each [FiltroDatos] = DataFilter),
				    #"Columnas quitadas2" = Table.RemoveColumns(FiltroDatos,{"FiltroDatos"})
				in
				    #"Columnas quitadas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

